skrypty/ui/misc.lua
=> fixing #448

Arkadia.xml
=> - add few draw weapon triggers

.gitattributes, Arkadia.xml, README.md, imie.txt, init.lua, mapper.lua, skrypty.lua, skrypty/utils/config/conf_loader.lua, skrypty/utils/installer/installer.lua
=> - bump verson to 4.1

Arkadia.xml, skrypty/inventory/help.lua, skrypty/inventory/special_inventory.lua
=> - add easy way to put down all magic items to chest

Arkadia.xml
=> - add another attack beep pattern

Arkadia.xml
=> - add invite bind from hidden

imie.txt, mapper/ui.lua, mapper/ui/update.lua
=> regular arrows for compass

Arkadia.xml
=> Blocker przy przemykaniu w czasie walki.

mapper.lua, skrypty.lua, skrypty/help.lua, skrypty/utils/installer/latest.lua
=> - release notes displayed on new version found

events.txt, init.lua, skrypty/ui/ui.lua, skrypty/utils/config/conf_loader.lua
- added events for scriptsLoaded, profileLoaded, uiReady
closes #449
=> - events review

mapper.lua, skrypty.lua
tie mapper version to scripts version
=> bump version to 4.5

Arkadia.xml, skrypty/misc/knowledge.lua
@mariuszjamro 
Jak mówiłem o tempTriggerach to miałem coś takiego na myśli. XML niestety jest modyfikowany przez enable i disable, co może być problemem jeżeli z jakiegoś powodu ten disable by się nie odpalił, bo włazi to w diffa potem przypadkowo :)
=> knowledge rework

Arkadia.xml
=> Blockery na dojenie krów.

skrypty/inventory.lua
=> init magics_data and magic_keys_data tables in inv

skrypty/inventory/special_inventory.lua, skrypty/ui/footer_info/info_updates.lua, skrypty/ui/footer_info/ui_footer_info.lua
- small fixes for footer info customization
- add exempt for brosza
=> small fixes for footer info customization

mapper/localizers/ships_buses/buses/maribor-grabowa.lua
=> fix localizer

Arkadia.xml
=> correct stats for rogata

Arkadia.xml, skrypty/inventory/equipment.lua
=> Damage level

Arkadia.xml, skrypty/ui/special_exits_follow.lua
=> better(?) binds

imie.txt, skrypty/utils/config/conf_loader.lua
bledy w pliku imie.txt nie sa sygnalizowane uzytkownikowi
przy okazji uproszczenie pliku imie.txt, pozbywamy sie funkcji, temp timerow etc.
=> Profile load improvement

imie.txt, scriptsList.lua, skrypty/people.lua, skrypty/people/core.lua, skrypty/ui/results_window.lua
Alternatywny sposób prezentacji wyników przeszukiwania bazy osób:
Można dać go domyślnie?
=> separate, optional sidebar for search results

config_schema.json, scriptsList.lua, skrypty/config/scripts_config.lua
Implementacja klasy `ScriptsConfig` ktora bedzie utrzymywala config, odpowiadala za update w skryptach, ladowala i zapisywala z i do pliku.
=> szkielet dla v2 config

Arkadia.xml
poprawka dla 1 i 2 poziomu oceny
=> dodanie oceny miecznika

skrypty/misc/improve/utils.lua, skrypty/team/next_attack_objs.lua
- mala rewizja do wiadomosci do `/nn`
- dodanie godziny do `misc.improve:seconds_to_formatted_string(seconds)`
=> rewizja do obliczania czasu i do msg

skrypty/character/profession.lua, skrypty/utils/config/conf_loader.lua
correct profileLoaded event fire timing
profession percentage will now be character dependant
=> zliczanie stazu dla roznych postaci oddzielnie

config_schema.json, skrypty/config/scripts_config.lua
Lista wszystkich zmiennych z `imie.txt`.
=> config schema do nowego systemu

Arkadia.xml, config_schema.json, skrypty/team.lua, skrypty/team/core.lua, skrypty/team/data_processing.lua, skrypty/ui/gags/color/color_other.lua
=> Added breaking defense marks to the states window

Arkadia.xml
=> dodanie brakujacego oglucha

Arkadia.xml
=> off pauser na podnosisz sie

Arkadia.xml
parowanie dodatkowe
wstep dla czlonkow zgromadzenia
closes #666
=> off pauser biurko na utopcach

skrypty/config/core.lua, skrypty/config/scripts_config.lua
- dodanie uruchamiania migracji na ladowaniu po triggerze z drukowaniem nowych zmiennych
- poprawienie zeby klikalne linki nie byly do konca linii na czarnym tle
-
=> Fixes for config v2

skrypty/misc/improve/gmcp_handler_improvement.lua
```
(skrypty): [26/09 18:55:47] Wlasnie wbiles postepy: nieznaczne (czas: 21:59)
```
=> time on improvement

mapper/highlighter.lua, skrypty/command_sequence.lua
poprawka dla higlightera + toggle
=> dodanie sekwencji komend

Arkadia.xml, skrypty/misc.lua
Poprawka triggerów związanych z tropieniem.
=> Tropienie poprawka

Arkadia.xml, skrypty/ui/gags/color/color_other.lua, skrypty/ui/gags/color/color_rozkazy.lua
=> poprawka gagu koloru zaslony z rozkazu

events.txt, mapper/blockers.lua, scriptsList.lua, skrypty/ui/gags/color/color_other.lua, skrypty/ui/no_weapon_alert.lua
=> - no weapon alert

skrypty/inventory/pretty_containers.lua
=> categorization improvement

README.md, init.lua
=> allow plugins do contribute to schema

Arkadia.xml, skrypty/ui/footer_main_modes/main_footer_updater.lua
=> double cover message fixed

Arkadia.xml
korekta na spec blekitnej tarczy
=> opal, korbacz wep on-off

Arkadia.xml, mapper/follow-texts/druchii.lua, mapper/follow-texts/non_standard.lua, scriptsList.lua
=> boat rowing

Arkadia.xml
=> poprawka regexpa na chwyt broni do oceny

config_schema.json, scriptsList.lua, skrypty/herbs/aliases.lua, skrypty/herbs/core.lua, skrypty/herbs/core_v2.lua, skrypty/herbs/db.lua, skrypty/herbs/herb_window.lua
`cpopup` nie dziala w oknie do kolejnego releasu mudleta (na PTB dziala)
=> add herb window functionality

config.md, skrypty/inventory/special_inventory.lua
correct check on magic correctness
=> add missing config.md entries

Arkadia.xml
=> tarcze bez ac

Arkadia.xml
=> parowanie magicznym puklerzem

Arkadia.xml
=> remove doubled trigger

skrypty/people.lua, skrypty/people/color_people.lua
=> color non db people

config.md, config_schema.json, skrypty/ui/states_window/ui_states_window.lua, skrypty/ui/talk_window/ui_talk_window.lua
=> no wrap for talk and states windows

Arkadia.xml, mapper/team/follow_team_family.lua
=> blockery, pausery

skrypty/ui/special_exits_follow.lua
=> fix missing trigger function

config.md, config_schema.json, scriptsList.lua, skrypty/ui/footer_elements/mail.lua, skrypty/ui/notification_center.lua
=> add notification center

skrypty/misc/improve/improve.lua
=> improvement index

skrypty/misc/counter/counter2.lua
=> Trolle jaskiniowe

.github/workflows/notify-discord.yml, skrypty.lua
=> workflow fix

ArkadiaScriptsInstaller.xml, config.md, config_schema.json, skrypty/team/core.lua, skrypty/ui/footer_info/info_updates.lua, skrypty/ui/footer_info/ui_footer_info.lua
add release state
add guilds indication field in schema
=> correct installer

skrypty/config/init.lua, skrypty/herbs/core.lua, skrypty/ui/gags/color/color_other.lua
=> No sub arkadia subbed herbs

mapper/ui/update.lua, skrypty/config/scripts_config.lua, skrypty/misc/improve/improve.lua
Poprawka na komendę `/postepy` gdy urywa się output.
Dodane ify na błędy które pojawiają się randomowo przy załadowaniu profilu.
=> Randomowe bledy

config.md, config_schema.json, skrypty/mail/mail_creator.lua
=> bugfix + justowanie

Arkadia.xml
=> fix oceny ubran

Arkadia.xml
=> Off pausers

Arkadia.xml, mapper/blockers.lua
=> dodanie blockerow i pauserow

config.md, config_schema.json, skrypty/herbs.lua, skrypty/herbs/aliases.lua, skrypty/herbs/aliases_v2.lua, skrypty/herbs/core.lua, skrypty/misc.lua
branie ziol jedna komenda
uzywaniu wielu ziol jedna komenda
zamykanie otwartych woreczkow
=> akcje przed braniem i po braniu ziol

Arkadia.xml
=> Gaszenie lampy

skrypty/misc/lang.lua
=> Język Ghassally

Arkadia.xml
=> bloker - wiatrak

Arkadia.xml, skrypty/ui/special_exits_follow.lua
=> Brakujace followy - Aver, baszta, gory Tilea

Arkadia.xml
=> Fix for kafar

Arkadia.xml, skrypty/ui/gags/color/color_innych_spece/bar.lua, skrypty/ui/gags/color/color_innych_spece/bar/ktos_spec.lua, skrypty/ui/gags/color/color_innych_spece/sprzet.lua, skrypty/ui/gags/color/color_moje_spece/bar.lua, skrypty/ui/gags/color/color_moje_spece/bar/ja_spec.lua, skrypty/ui/gags/color/color_moje_spece/sprzet.lua
=> Ogluch barba i granita w oknie kondycji

config.md, config_schema.json, skrypty/team.lua, skrypty/team/core.lua
=> dodana opcja wybrania ciagu znakow dla naszej postaci w oknie kondycji

Arkadia.xml
=> Uzupelnienie blockers

Arkadia.xml, skrypty/ui/gags/color/color_cele.lua
close #926
Usunelem ifa bo dotyczy tylko przypadku gdy przywodca TWOJEJ druzyny zatakuje ciebie, a uproscilo patterny.
=> RA wskazanie celu ataku

Arkadia.xml, skrypty/team.lua
Komenda druzyna wyczysci ateam.team ze wszystkich, ktorzy opuscili juz druzyne => /obecni bedzie poprawnie wyswiatlalo nieobecnych
=> druzyna aktualizuje sklad

Arkadia.xml, skrypty/inventory/kowal.lua, skrypty/inventory/lampa.lua, skrypty/misc/food.lua
close #1012 
close #1018 
close #1020
=> Drobne zmiany

Arkadia.xml
=> Numeryczna wartość "ledwo muska" dla mistera pojawia się dwukrotnie

Arkadia.xml, scriptsList.lua, skrypty/world/brokilon.lua
=> strzaly, pulapki

mapper/core.lua, mapper/ui/update.lua
=> na rozy pojawi sie pierwsze wystapienie prowadzace do danej lokacji

Arkadia.xml
=> Bloki mapy

skrypty/misc/skill.lua
=> umy na kolorowo

Arkadia.xml, skrypty/misc/lvl_calc.lua
usuniecie triggera na poziom z opisu
=> dodanie brakujacego nawiasu

Arkadia.xml
fixes #1054
fixes #1053
fixes #1057
=> Poprawki zwiazane z podazaniem na Bacalli i inne podobne

Arkadia.xml
=> Spec goblina nie bedzie juz czasem mial podwojnej wartosci

Arkadia.xml, scriptsList.lua, skrypty/herbs/herbs_effects.lua
=> herb-effects

Arkadia.xml
=> Przybijające do brzegu statki pokazują trzy bindy

Arkadia.xml, skrypty/ui/special_exits_follow.lua
=> Przeplywanie - bindowanie

Arkadia.xml
=> bloker poruszania sie

Arkadia.xml, mapper/directions-ui.lua
=> pokazywanie kierunkow - brakuje góra/dół

Arkadia.xml, skrypty/inventory/equipment.lua
=> Podwojne wyswietlenie pojemnika

Arkadia.xml, skrypty/ui/gags/color/color_npc.lua
=> Spec goblinoidów ma błędne wartości

Arkadia.xml, config.md, scriptsList.lua, skrypty/packages/assistant.lua, skrypty/people.lua, skrypty/people/mail.lua
- informacja o pobranej paczce
- zapamietywanie gdzie paczka zostala doreczona
- pokazywanie sciezki do celu
=> Package assistant

Arkadia.xml
=> Asikowe - Raon

Arkadia.xml, scriptsList.lua, skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_maczugi.lua, skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_mloty.lua
=> dwusegmentowa maczuga

skrypty/ui.lua
=> naprawa bledu na zmiane stanow paska przy maksymalnym ukryciu

mapper/localization.lua, mapper/map.lua, scriptsList.lua, skrypty/ui/talk_window/gmcp_msgs.lua
wstep, zbieranie shortow + wyjsc do dodania
=> mozliwosc lokalizacji z bazy shortow+wyjsc

Arkadia.xml
=> Usunięty komunikat "NI" gdy nie ma nic do naprawy

Arkadia.xml, skrypty/ui/misc.lua
Kolorowanie zmęczenia w tekście komend które pokazują innym zmęczenie
Dane testowe
```
/fake Charakterystycznym wojskowym tonem meldujesz, ze jestes w pelni wypoczety.
/fake Charakterystycznym wojskowym tonem meldujesz, ze jestes wypoczety.
/fake Charakterystycznym wojskowym tonem meldujesz, ze jestes troche zmeczony.
/fake Charakterystycznym wojskowym tonem meldujesz, ze jestes zmeczony.
/fake Zziajanym glosem meldujesz, ze jestes bardzo zmeczony.
/fake Zziajanym glosem meldujesz, ze jestes nieco wyczerpany.
/fake Zziajanym glosem meldujesz, ze jestes wyczerpany.
/fake Zziajanym glosem meldujesz, ze jestes bardzo wyczerpany.
/fake Zziajanym glosem meldujesz, ze jestes wycienczony.
/fake Zziajanym glosem meldujesz, ze jestes calkowicie wycienczony.
/fake Charakterystycznym wojskowym tonem …
```
=> Kolorowanie poziomu zmęczenia w komendach nazmeczenie i stodpocznij

Arkadia.xml
=> ogladanie plecaka

skrypty/ui/special_exits_follow.lua
=> Bindowanie dwóch przejść

Arkadia.xml
=> unblocker mapy

Arkadia.xml, skrypty/ui/gags/color/color_innych_spece/sprzet.lua
=> dodac oglucha szczerby

skrypty/transport/ride.lua
pasek postepu wyczysci sie po dwukrotnym przekroczeniu przewidywanego czasu
=> fix na wysiadanie z dylizansu z druzyna + wyskakiwania za burte

Arkadia.xml
=> przedstawianie

skrypty/people/color_people.lua
=> kolorowanie wrogow

Arkadia.xml, skrypty/ui/misc.lua, skrypty/world/brokilon.lua
fix brak druzyny
fix trucizna gag
fix brok
=> minor fixes

Arkadia.xml, config.md, config_schema.json, scriptsList.lua, skrypty/config/core.lua, skrypty/config/scripts_config.lua, skrypty/herbs/core_v2.lua, skrypty/herbs/herb_window.lua, skrypty/inventory/bags.lua, skrypty/inventory/bags/help.lua, skrypty/inventory/bags/lang.lua, skrypty/inventory/bags/setup.lua, skrypty/inventory/collect.lua, skrypty/logger.lua, skrypty/misc/cutting.lua, skrypty/misc/improve/gmcp_handler_improvement.lua, skrypty/misc/wycinanie-triggers.lua, skrypty/transport/ride.lua, skrypty/ui/auto_wrap.lua, skrypty/ui/combat_window.lua, skrypty/ui/states_window/ui_states_window.lua, skrypty/ui/talk_window/ui_talk_window.lua, skrypty/ui/ui.lua, skrypty/utils.lua, ui/window.lua, ui/window_manager.lua
poprawione zapisywanie globalnych postepow przy wylaczonej formie
latwe ustawianie pojemnikow aliasem /pojemnik
poprawka na bledy dylizansu salignac-elfka
poprawki zwiazane z ustwieniami wrapu dla okien
mozliwosc wylaczenia wrapu w oknie walki
=> blad ladowania configu bedzie od razu widoczny

skrypty/inventory/bags/core.lua, skrypty/inventory/bags/setup.lua, skrypty/logger.lua, skrypty/ui/combat_window.lua, skrypty/ui/states_window/window_util.lua
/pojemnik bedzie ustawial domyslnie akcje przed i po (otwieranie i zamykanie pojemnika)
window_modify - poprawa bledu ktory nie pozwalal na zmiane pierwszej linii
=> poprawka dla loggera

config.md, config_schema.json, skrypty/team/core.lua
applies to objects in team and normal tables
=> stealth brackets in states window, with cfg

config.md, config_schema.json, skrypty/team/core.lua
ramka umieszczona miedzy aliasami a stealth/hp
=> wyswietlanie sumy atakujacych wrogow w oknie kondycji, z konfigiem

Arkadia.xml, skrypty/ui/gags/color/color_moje_spece/sprzet.lua
``` Masz wrazenie, ze trucizna dostala sie do krwi przeciwnika.```
=> Kolorowanie zatrucia przeciwnika przez broń

Arkadia.xml, skrypty/ui/gags/color/color_innych_spece/bar/ktos_spec.lua, skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_maczugi.lua, skrypty/ui/gags/color/color_moje_spece/bar.lua
Zamiana speca barba na regexpy
dodane bronie specjalne do maczug:
dlugi_runiczny_korbacz
krysztalowy_swietlisty_korbacz
lodowata_dluga_maczuga
czarnoblekitny_pulsujacy_morgenstern (WIP)
=> Barbarzynca

Arkadia.xml
=> nowy bloker

Arkadia.xml
=> za dużo backslashy

mapper/db/core.lua
Zmiana nie dotyczy id lokacji na której stoimy, tylko lokacji o podanym w parametrze room_id.
=> change room_id, not the current location

skrypty/misc/food.lua
Wszyscy zawsze siadają na tym nieszczęsnym ostatnim miejscu.
Taki drobiazg, żeby się inne fotele też zaczęły wycierać. ;)
=> siadaj w różnych miejscach

Arkadia.xml, skrypty/ui/gags/color/color_innych_ciosy.lua
Przeniesienie sily ciosow draga do pozostalych broni
close #1321
=> Kikimory sila ciosow

Arkadia.xml, skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_miecze.lua, skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_mloty.lua
=> Spec miecznika - finisher

Arkadia.xml, skrypty.lua, skrypty/ui/footer_elements.lua, skrypty/ui/gmcp_handlers/guard_state.lua, skrypty/ui/gmcp_handlers/hidden_state.lua, skrypty/ui/gmcp_handlers/order_state.lua, skrypty/ui/states_window/ui_states_window_navbar.lua, skrypty/ui/ui_new_location_event.lua
Zastapienie timerow NamedTimer'ami, uproszczenie kodu
=> Better UI states

Arkadia.xml
=> Bloker na korkostatku

Arkadia.xml
Zmiana niepotrzebnych regexpów, głównie na substringi.
Wygładzenie kilku regexpów.
=> Refaktoring części blockerów + kolejne opisy speca partyzanta z 3os

Arkadia.xml, skrypty/ui/gags/color/color_innych_ciosy.lua, skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_drzewce.lua, skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_miecze.lua, skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_mloty.lua, skrypty/ui/gags/color/magics.lua, skrypty/ui/gags/gags.lua
=> partyzana, szamszir, archaiczny topor i poprawki

skrypty/people/core.lua
=> dodaj_osobe - bedzie pokazywalo id dodanej osoby

Arkadia.xml, skrypty/ui/gags/color/color_innych_ciosy.lua
=> Miecznik - cios konczacy

scriptsList.lua, skrypty/dev/core.lua, skrypty/misc/lvl_calc.lua
dodanie /fake PPM z schowka w linii komend
=> usuniecie lini debug w liczniku cech

Arkadia.xml, skrypty/misc.lua
=> dodatkowe follow bindy

Arkadia.xml, mapper/utils.lua, skrypty/misc.lua
=> Follow - pulapka kolo Saurgla, widoczne kierunki na Drodze Czaszek

skrypty/misc/lvl_calc.lua
Uproszczenie kodu licznika cech, pokazywanie zmian w cechach.
fixes #1378
=> Licznikcechy

mapper/events/custom-events/binds.lua, mapper/events/custom-events/gates.lua, mapper/events/custom-events/water.lua, mapper/gates.lua, skrypty/inventory/collect.lua, skrypty/inventory/lampa.lua, skrypty/misc/improve/improve.lua, skrypty/transport/ride.lua, skrypty/ui/gags/color/color_other.lua, skrypty/utils/keybinds.lua, skrypty/utils/keybinds_ship.lua, skrypty/world/brokilon.lua
One functional echo bind for all,
Suma postepow danego dnia w /postepy
=> One bind4all

Arkadia.xml, skrypty/misc/lvl_calc.lua
closes #1334, closes #1389, closes #1391, closes #1399, closes #1400, closes #1403
=> Followy, blockery, /cechy

events.md, skrypty/misc/improve/gmcp_handler_improvement.lua
Event podnoszony w momencie gdy mamy pewność że i jak duże postępy właśnie wskoczyły.
=> improveLevelGained

Arkadia.xml
Poprawka z https://github.com/tjurczyk/arkadia/issues/1448
=> Poprawa bindowania przejscia za glazy

Arkadia.xml
https://github.com/tjurczyk/arkadia/issues/409
=> Dodanie binda na dobywanie dla ghuli

config.md, config_schema.json, mapper/path.lua
z dodanym helpem
nie ustawialem color2, nie widzialem potrzeby :)
=> kolor podswietlania lazika na mapie wyciagniety do confa

Arkadia.xml, mapper/highlighter.lua, skrypty/character/combat_state.lua, skrypty/invalid_commands.lua, skrypty/inventory/pretty_containers.lua, skrypty/misc/item_damaged.lua, skrypty/misc/knowledge/knowledge.lua, skrypty/misc/lvl_calc.lua, skrypty/ui/gags/color/color_innych_spece/leg/ktos_spec.lua, skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_maczugi.lua, skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_miecze.lua, skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_mloty.lua, skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_sztylety.lua, skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_topory.lua, skrypty/ui/gags/color/color_moje_spece/noz.lua, skrypty/ui/gags/color/magics.lua, skrypty/ui/gags/gags.lua
Przepoprawiony spec nozownikai legionisty, poprawki do regexpow gagow, opcja do ich debuggowania, rozne inne
=> Zbiorcze poprawki

Arkadia.xml, config.md, skrypty/invalid_commands.lua, skrypty/ui/gags/color/color_innych_ciosy.lua, skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_maczugi.lua
fixes #1476 
@rawisz @axesider
=> fix ciosy bagiennika + pisanie listu z szablonem pergamin

Arkadia.xml
=> fix hit coloring

Arkadia.xml
Nie łapało plecaka z takim opisem:
Otwarty praktyczny plecak ze skory szczura zawiera ciezki oszlifowany miecz, poreczny kompas, kolista zdobiona tarcze, wypukla skorupowa tarcze, zoltawa gruszke i dwa srebrzyste kanciaste mloty bojowe.
=> Plecaki z ZH

events.md, skrypty/herbs/core_v2.lua
- ilosc ziol w woreczku
- event na ilosc ziol i ziola w woreczku
=> add herbs total in bag

Arkadia.xml
https://github.com/tjurczyk/arkadia/issues/1541
=> Fix brakujacy blocker

Arkadia.xml
https://github.com/tjurczyk/arkadia/issues/1531
=> Add missing weapon on patterns

skrypty/misc/knowledge/libraries.lua
Pozwala na usuniecie wpisow z bazy. Dzieki temu bedzie mozliwe usuniecie niedostepnych juz bibliotek (zmieniona nazwa/lokacja).
=> add removing entry

skrypty/misc/counter.lua, skrypty/misc/counter/counter2.lua
=> Revert "final fix"

skrypty/misc/counter.lua, skrypty/misc/counter/counter2.lua
=> Revert "one more fix for db refactor"

.github/workflows/Arkadia.xsd, .github/workflows/validate-xml.yml, .gitignore, Arkadia.xml, skrypty/event_register.lua
fixes #1520 
fixes #1523
fixes #1504
fixes #1470
=> Some fixes
