- Arkadia.xml
Poprawka wzorca by kompas łapał rozgałęzienia tunelu:  `...tunel rozwidlajacy sie na..`
```
Zatrzymales sie tutaj by chwile odpoczac. Przy okazji przypatrujesz sie miejscu, w ktorym stoisz.
Przy kazdym ruchu pod nogami chrzeszcza ci drobne kamienie i skalny mial, ktore powietrze i woda 
wyluskaly ze scian. Co i rusz potykasz sie o wystepy powstale w wyniku wodnej erozji. Dawno nikt nie 
porzadkowal tej czesci korytarza. Czyzby nikt o niej nie pamietal?
W gestych ciemnosciach dostrzegasz tunel rozwidlajacy sie na polnoc, poludniowy-wschod i zachod.
```
> Poprawka na kierunki w tunelu Karak Varn - Karak Kadrin

- Arkadia.xml
- skrypty/misc/knowledge.lua
Ułatwienia do zglębiania wiedzy w bibliotekach.
Komenda `zglebiaj` wypisuje dostępne do zgłębiania tematy w jednej linii i wymaga podania dokładniej takiej samej nazwy żeby daną wiedzę zgłębić.
Rezultat komendy jest rozdzielany na wiersze oraz numerowany. Dostępny jest alias który pozwala zgłębiać wiedzę o podanym numerze (bez podawania pełnej nazwy). 
Poprzednia (pełna) komenda dalej działa, czyli można dalej użyć `zglebiaj wiedze o goblinoidach`
> Ulepszenie zgłębiania wiedzy

- Arkadia.xml
Jesli na lokacji jest np siec rybacka to bindowanie nie wystepuje, bo nie ma kropki.
> poprawione bindowanie na statki

- Arkadia.xml
Poprawka, aby lapalo statki:
- kropka, albo
- przecinek, albo
- ` i`
> poprawka regexow do statkow

- skrypty/inventory/collect.lua
Przed zmianami `/zbierz` wsadzało do pojemnika po kazdym ciele osobno:
```
/zbierz
policz wszystkie ciala
Doliczyles sie czterech sztuk.
wez monety z pierwszego ciala
wloz monety do plecaka
wez monety z drugiego ciala
wloz monety do plecaka
wez monety z trzeciego ciala
wloz monety do plecaka
wez monety z czwartego ciala
wloz monety do plecaka
```
Po zmianach zbierz wsadza monety/kamienie tylko raz przy ostatnim ciele:
```
/zbierz
policz wszystkie ciala
Doliczyles sie czterech sztuk.
wez monety z pierwszego ciala
wez monety z drugiego ciala
wez monety z trzeciego ciala
wez monety z czwartego ciala
wloz monety do plecaka
```
> Wloz do torby raz po zebraniu z wszystkich cial a nie po kazdym ciele osobno

- skrypty/herbs/core_v2.lua
Branie ziol z woreczkow to biernik, a nie mianownik.
> fix ziola v2

- skrypty/team/enemy_count_tracker.lua
Obsluga sytuacji, kiedy wrzuci sie kolejke wrogow, ale na lokacje wchodza nowe postacie, ktore staja sie wrogami.
> kolejkowanie przy nowych wrogach na lokacji

- README.md
/ziola_buduj - opcja szerokość na Arkadii musi być ustawiona na 0, inaczej komenda nie działa poprawnie. Informacja w README.md
> /ziola_buduj

- config.md
- config_schema.json
- scriptsList.lua
- skrypty/ui/auto_wrap.lua
automatyczny line wrap dla głównego okna, zależny od jego szerokości.
domyślnie wyłączony
> auto wrap in main window

- Arkadia.xml
Pozostałe warianty opisu ciosu dla jasniejacego zdobionego jatagana.
```
/fake Jasniejaca luna znaczy powietrze, gdy dlugim cieciem jasniejacego zdobionego jatagana ledwo muskasz ciemnookiego
/fake Jasniejaca luna znaczy powietrze, gdy dlugim cieciem jasniejacego zdobionego jatagana lekko ranisz ciemnookiego
/fake Jasniejaca luna znaczy powietrze, gdy dlugim cieciem jasniejacego zdobionego jatagana masakrujesz czerwonookiego
/fake Jasniejaca luna znaczy powietrze, gdy dlugim cieciem jasniejacego zdobionego jatagana ranisz ciemnookiego
/fake Jasniejaca luna znaczy powietrze, gdy szybkim pchnieciem jasniejacego zdobionego jatagana ledwo muskasz ciemnookiego
/fake Jasniejaca luna znaczy powietrze, gdy szybkim pchnieciem jasniejacego zdobionego jatagana lekko ranisz ciemnookiego
/fake …
```
> Poprawki oznaczania ciosów jataganem.

- Arkadia.xml
Test:
```
/fake Nagle wyszkolony jednooki mezczyzna wykonuje zamaszysty cios waskim krotkim jataganem celujac w XXX, lecz ten paruje go adamantytowym mlotem bojowym.
/fake Nagle grozny potezny mezczyzna wykonuje zamaszysty cios guzowata sekata pala celujac w XXX, lecz uderzenie zatrzymuje sie na jego pelnej bialej zbroi rycerskiej z herbem.
/fake Nagle grozny potezny mezczyzna wykonuje zamaszysty cios guzowata sekata pala celujac w XXX, lecz uderzenie zatrzymuje sie na jej bialoblekitnej smoczej zbroi.
/fake Cios dosiega dlugowlosym urodziwym mezczyzna, lecz zeslizguje sie po jego stalowej mocnej przylbicy.
```
> Poprawki oznaczania parowania.

- Arkadia.xml
- skrypty/mail/mail_creator.lua
Nie wyswietlalo lini: Do, Temat i CC dla rozmiaru czcionki wiekszej od 10 (w win10 domyslnie ustawialo 12).
Ustawianie rozmiaru czcionki takiej jak glowne okno.
Opcja edycji ~d usuwa ostatnio dodana linie wiadomosci.
/list [adresat] [temat] otworzy okno z wypelnionymi headerami (przyklad zastosowania - alias msg = /list obecni Koperta)
> List poprawki

- Arkadia.xml
- skrypty/ui/misc/ptakopodobny.lua
1. Wywalam informacje "uciekaj" bo po ostatnich zmianach już nie da się uciec oraz zmieniam formatowanie wiadomości na standardowe "CZAR".
2. Dodaje bloker
```
Nie mozesz sie tam udac, gdyz pod wplywem spojrzenia zoltych slepi zlowrogiego ptakopodobnego mezczyzny twe cialo 
zamiera w bezruchu, zas w glowie jest jedynie pustka.
```
> Poprawki na ptakopodobnego.

- skrypty/team/last_seen_hp.lua
Zadziała zarówno `/hp Imie` jak i `/hp imie`
> Ignorowanie wielkości znaku przy podawaniu imienia w komendzie /hp

- Arkadia.xml
Nie odpala `^[ &gt;]*Niestety, wyglada na to, ze wiecej osob niz jedna sie tam nie zmiesci\.$` jako regex.
> Nie odpala sie bloker w tunelu

- Arkadia.xml
- skrypty/misc/attack_beep.lua
Po to by dało się przetestować czy słychać beepa nie czekając aż Zetu cię zaatakuje na idlu.
> Komenda /beep do przetestowania beepa

- Arkadia.xml
Nie łapało jak nieprzedstawiona osoba zaprasza do drużyny.
Nie łapało jak nieprzedstawiona osoba porzuca drużynę lub jest zmuszona do jej opuszczenia.
Test:
```
/fake Rono zaprasza cie do swojej druzyny.
/fake [Rono] zaprasza cie do swojej druzyny.
/fake Barczysty czarnooki mezczyzna zaprasza cie do swojej druzyny.
/fake Rono rozwiazuje druzyne.
/fake [Rono] rozwiazuje druzyne.
/fake Barczysty czarnooki mezczyzna rozwiazuje druzyne.
/fake Rono porzuca twoja druzyne.
/fake [Rono] porzuca twoja druzyne.
/fake Barczysty czarnooki mezczyzna porzuca twoja druzyne.
/fake Zmuszasz Rono do opuszczenia druzyny.
/fake Zmuszasz [Rono] do opuszczenia druzyny.
/fake Zmuszasz barczystego czarnookiego mezczyzne do opuszczenia druzyny.
```
> Poprawki na zapraszanie/opuszczanie drużyny przez nieprzedstawione postacie

- skrypty/inventory/bags.lua
Ostatnio różni dziwni ludzie rozkładają plecaki/sakiewki w bankach i na statkach żeby eksploitować sytuacje gdzie denominując pieniądze lub kupując bilet na statek odkładasz pieniądze do leżącego plecaka zamiast do swojego. 
Proponuje wymusić by komendy w skryptach działały tylko na pojemnikach które postać ma przy sobie. 
```
wem
wez monety z swojej sakiewki
Bierzesz dziewietnascie srebrnych monet, mithrylowa monete, wiele zlotych monet i piec miedzianych monet z otwartej
porzadnej czarnej sakiewki z runami.
wlm
wloz monety do swojej sakiewki
Wkladasz piec miedzianych monet, wiele zlotych monet, mithrylowa monete i 24 srebrne monety do otwartej porzadnej
czarnej sakiewki z runami.
```
> Komendy dot. pojemnikow powinny dzialac tylko na pojemnikach ktore postac ma przy sobie

- config.md
- scriptsList.lua
- skrypty/ui/footer_info/info_updates.lua
- skrypty/ui/footer_info/ui_footer_info.lua
- skrypty/ui/gmcp_handlers/gmcp_room_time_handler.lua
- skrypty/ui/gmcp_handlers/gmcp_state_handler.lua
Dane pobierane z ``gmcp.room.time``. Klucze konfiguracyjne footera:
``daylight`` - pora dnia (dzień/noc)
``season`` - pora roku
> Obsługa pory dnia i pory roku w footerze przez gmcp.

- Arkadia.xml
- skrypty/ui/gags/color/color_innych_ciosy.lua
- skrypty/ui/gags/color/color_moje_ciosy.lua
- skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_drzewce.lua
- skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_miecze.lua
- skrypty/ui/gags/color/color_moje_ciosy/niestandardowe_mloty.lua
- skrypty/ui/gags/color/magics.lua
Sila ciosow dla: upiorny chepesz/wlocznia, jasniacy mlot/miecz/wlocznia, adamantytowy mlot, kruczoczarny miecz, srebrzysta kosa, jadeitowy palasz,  misterny harpun, kosciany topor, wulkaniczny kindzal, kosciane berlo 3os, espadon 3os., arlekiny 3os., trojzab 3os., adamantytowa partyzana 3os., kobaltowa halabarda 3os.
close #1328
close #1279
> Sila ciosow niestandardowych broni

- mapper/shortcuts.lua
/pokaz_skroty wyświetla teraz je w kolejności dodawania obiektów. Mocno nieczytelne przy większej liście.
Alfabetycznie wychodzi lepiej.
> sortuj skróty w /pokaz_skroty

- skrypty/ingress.lua
po przejsciu do lokacji, w ktorej nie widac dostepnych wyjsc, trzeba czyscic amap.localization.current_exit
> Gmcp msgs current exits cleanup

- Arkadia.xml
Poprawiłem wyłapywanie w 1szej i 3ciej osobie jednego z kończących ciosów misternego obosiecznego topora:
> Poprawka wyłapywania ciosów misternego obosiecznego topora.

- skrypty/utils/installer/plugins.lua
U mnie ten regexp Twój jakoś nie działa ani dla pluginu hostowanego na gitlabie, ani dla lokalnych ścieżek.
```lua url="https://gitlab.com/api/v4/projects/12345/packages/generic/plugin/v2.1.17/plugin_nazwa.zip"
lua display(url)
"https://gitlab.com/api/v4/projects/12345/packages/generic/plugin/v2.1.17/plugin_nazwa.zip"
lua file_name=url:match("/([^/]+)(?.*)$")
lua display(file_name)
nil
...
lua file_name = url:match("([^/]+)$")
lua display(file_name)
"plugin_nazwa.zip"
lua  plugin_name, extension = file_name:gmatch("(.+)%.(.+)$")()
lua display(plugin_name)
"plugin_nazwa"
lua display(extension)
"zip"
```
> regmatch gdy nie github

- Arkadia.xml
- skrypty/herbs/smart_application.lua
- skrypty/packages/assistant.lua
- Update triggers regex: include optional 'z umbem' in item decomposition and brackets around direction pointer.
- Minor whitespace cleanup in `assistant.lua`.
fixes #1514
fixes #1640
fixes #1522
> - Add check for empty herbs database in `smart_apply` function.
